version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - gosec
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net.Conn).Close
        - (*github.com/jackc/pgx/v5.Tx).Rollback
        - (github.com/joacominatel/pulse/internal/application.UnitOfWork).Rollback
        - github.com/joho/godotenv.Load
        - (*github.com/joacominatel/pulse/internal/infrastructure/cache.RedisClient).Close
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    gosec:
      excludes:
        - G104
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: increment-decrement
        - name: var-declaration
        - name: unexported-return
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
formatters:
  enable:
    - gofmt
    - goimports
