package domain

import (
	"context"
	"time"
)

// UserRepository defines the interface for user persistence.
// implementations live in infrastructure, not in domain.
type UserRepository interface {
	// FindByID retrieves a user by their internal ID.
	FindByID(ctx context.Context, id UserID) (*User, error)

	// FindByExternalID retrieves a user by their external auth provider ID.
	FindByExternalID(ctx context.Context, externalID string) (*User, error)

	// FindByUsername retrieves a user by their username.
	FindByUsername(ctx context.Context, username Username) (*User, error)

	// Save persists a user (insert or update).
	Save(ctx context.Context, user *User) error

	// Exists checks if a user with the given ID exists.
	Exists(ctx context.Context, id UserID) (bool, error)
}

// CommunityRepository defines the interface for community persistence.
type CommunityRepository interface {
	// FindByID retrieves a community by its ID.
	FindByID(ctx context.Context, id CommunityID) (*Community, error)

	// FindByIDs retrieves multiple communities by their IDs.
	// maintains the order of the input IDs.
	FindByIDs(ctx context.Context, ids []CommunityID) ([]*Community, error)

	// FindBySlug retrieves a community by its URL-friendly slug.
	FindBySlug(ctx context.Context, slug Slug) (*Community, error)

	// Save persists a community (insert or update).
	Save(ctx context.Context, community *Community) error

	// Exists checks if a community with the given ID exists.
	Exists(ctx context.Context, id CommunityID) (bool, error)

	// ListByMomentum returns active communities ordered by momentum.
	// limit controls max results, offset for pagination.
	ListByMomentum(ctx context.Context, limit, offset int) ([]*Community, error)

	// UpdateMomentum updates just the momentum fields for a community.
	// more efficient than full save for background jobs.
	UpdateMomentum(ctx context.Context, id CommunityID, momentum Momentum) error
}

// ActivityEventRepository defines the interface for activity event persistence.
type ActivityEventRepository interface {
	// Save persists a new activity event.
	// events are append-only, so no update method.
	Save(ctx context.Context, event *ActivityEvent) error

	// SaveBatch persists multiple activity events in a single transaction.
	// more efficient than individual saves for bulk operations.
	SaveBatch(ctx context.Context, events []*ActivityEvent) error

	// FindByCommunity retrieves events for a community within a time window.
	// ordered by created_at descending (newest first).
	FindByCommunity(ctx context.Context, communityID CommunityID, since time.Time, limit int) ([]*ActivityEvent, error)

	// FindByUser retrieves events generated by a user.
	// ordered by created_at descending (newest first).
	FindByUser(ctx context.Context, userID UserID, limit int) ([]*ActivityEvent, error)

	// CountByCommunity counts events for a community within a time window.
	CountByCommunity(ctx context.Context, communityID CommunityID, since time.Time) (int64, error)

	// SumWeightsByCommunity calculates the total weighted momentum contribution
	// for a community within a time window.
	SumWeightsByCommunity(ctx context.Context, communityID CommunityID, since time.Time) (float64, error)
}
